const projectsData = [
  {
    name: 'Jogo Multiplayer',
    tech: 'NextJS NodeJS/Socket.IO',
    url: 'https://github.com/lucopdev/hash_game_1.1',
    images: ['./assets/image/hashgame.png'],
    module: 'FullStack',
    repository: 'https://github.com/lucopdev/hash_game_1.1',
  },
  {
    name: 'Carwish',
    tech: 'Flutter e NodeJS',
    url: 'https://github.com/lucopdev/Carwish',
    images: [
      './assets/image/carwish/carwish001.png',
      './assets/image/carwish/carwish002.png',
      './assets/image/carwish/carwish003.png'
    ],
    module: 'FullStack',
    repository: 'https://github.com/lucopdev/Carwish',
  },
  {
    name: 'LucopGen',
    tech: 'TauriJS e NodeJS',
    url: 'https://github.com/lucopdev/lucopgen-frontend',
    images: ['./assets/image/lucopgen.png'],
    module: 'FullStack',
    repository: 'https://github.com/lucopdev/lucopgen-frontend',
  },
  {
    name: 'Amazon Test',
    tech: 'React',
    url: 'https://amazontest.surge.sh/',
    images: ['./assets/image/amazontest.png'],
    module: 'Frontend',
    repository: 'https://github.com/lucopdev/amazon-mainpage-test',
  },
  {
    name: 'Cointrack',
    tech: 'flutter',
    url: 'https://cointrack.surge.sh/',
    images: ['./assets/image/cointrack.jpeg'],
    module: 'Frontend',
    repository: 'https://github.com/lucopdev/cointrack',
  },
  {
    name: 'Recipe App',
    tech: 'React',
    url: 'https://lucopdev-recipesapp.surge.sh/',
    images: ['./assets/image/recipes-app.png'],
    module: 'Frontend',
    repository: 'https://github.com/lucopdev/project-recipes-app',
  },
  {
    name: 'TrybeTunes',
    tech: 'React',
    url: 'http://lucopdev-trybetunes.surge.sh',
    images: ['./assets/image/trybetunes.png'],
    module: 'Frontend',
    repository: 'https://github.com/lucopdev/trybetunes',
  },
  {
    name: 'Tryunfo',
    tech: 'React',
    url: 'https://lucopdev-tryunfo.surge.sh/',
    images: ['./assets/image/tryunfo.png'],
    module: 'Frontend',
    repository: 'https://github.com/lucopdev/tryunfo',
  },
  {
    name: 'TrybeWallet',
    tech: 'React',
    url: 'https://lucopdev-trybewallet.surge.sh/',
    images: ['./assets/image/trybewallet.png'],
    module: 'Frontend',
    repository: 'https://github.com/lucopdev/trybewallet',
  },
  {
    name: 'Trivia',
    tech: 'React',
    url: 'https://lucopdev-trivia.surge.sh/',
    images: ['./assets/image/trivia.png'],
    module: 'Frontend',
    repository: 'https://github.com/lucopdev/project-trivia',
  },
  {
    name: 'Meme Generator',
    tech: 'JavaScript',
    url: 'https://lucopdev-memegenerator.surge.sh/',
    images: ['./assets/image/memegenerator.png'],
    module: 'Fundaments',
    repository: 'https://github.com/lucopdev/project-meme-generator',
  },
  {
    name: 'PIXEL-ART',
    tech: 'JavaScript',
    url: 'https://lucopdev-pixelart.surge.sh/',
    images: ['./assets/image/pixelart.png'],
    module: 'Fundaments',
    repository: 'https://github.com/lucopdev/pixel-art',
  },
];

export default projectsData;